### ISSUE TITLE
Double check-mark buttons when editing

### ISSUE THREAD

**Issue by ticalc-travis** [Silind/Hue-Debugger-UI#2]
When editing certain items (such as values under “lights/\<ID\>/state”), I sometimes get two green checkmark buttons, as shown in the screenshot. I'm not clear on the difference between these two, and they don't appear to have any descriptive tooltips. The lower one seems to work as expected, but clicking the upper one causes an error in the console like the following:

    error: type 7
    address: /lights/12/state/on
    description: invalid value,  true }, for parameter, on

I'm not sure if this is a bug or if the other green button is supposed to be an alternate function. If it's an intentional feature, I think the UI could be a bit more clear.

![image](https://user-images.githubusercontent.com/3048435/50389010-99439300-06e9-11e9-897c-32aca4f9b00c.png)

**Comment by Silind** [comment]
Thanks for creating this issue, @ticalc-travis, it is much appreciated.

To clarify; the two different checkmark buttons do in fact lead to slightly different behavior.
The top one will create a value that is a string, no matter the input, whereas the lower one will try to interpret the input and parse the datatype. This is why an 'int 1' is suggested in the above example.

With certain resources, the Hue Bridge expects a string value containing a number or a boolean, while with other resources it expects a certain datatype, e.g. a boolean. The latter is the case resulting in the error you get from the console in the above example.

However, I see why this is too ambiguous, and that the UI needs to be much more clear about this, so I am glad you created this issue.
