### ISSUE TITLE
Direct editing of regions as JSON, etc.

### ISSUE THREAD

**Issue by ticalc-travis** [Silind/Hue-Debugger-UI#5]
Just an idea based on how HTML inspection tools work in browsers like Firefox/Chrome/Chromium where you have a tree view of the document and can select “Edit as HTML” to edit it as text: It might be nice to be able to take a node and its children in the view and edit the chunk as JSON in a textarea. This could be used to make several changes at once quickly. It would also allow for convenient clipboard copy/paste. It’d be a nice feature, though would probably be some work since you’d have to parse it, have error handling, and logic to figure out how to translate the complete chunk into the proper sequence of bridge API calls.

**Comment by lucbloom** [comment]
Was this added or even considered? I'm having trouble adding a new variable or object. Is that possible in the current version?
